# Generated by Django 5.0.3 on 2024-04-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_hrprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='full_name',
        ),
    ]
